local colors = {
  black = "#000000",
  medium_gray = "#767676",
  white = "#F1F1F1",
  actual_white = "#FFFFFF",
  subtle_black = "#303030",
  light_black = "#262626",
  lighter_black = "#4E4E4E",
  light_gray = "#A8A8A8",
  lighter_gray = "#C6C6C6",
  lightest_gray = "#EEEEEE",
  pink = "#fb007a",
  dark_red = "#A22225",
  light_red = "#FF5254",
  lighter_red = "#FB6C6D",
  darkest_red = "#390000",
  lightest_red = "#FFE7E7",
  darker_blue = "#005F87",
  dark_blue = "#008EC4",
  blue = "#20BBFC",
  light_blue = "#b6d6fd",
  dark_cyan = "#20A5BA",
  light_cyan = "#4FB8CC",
  dark_green = "#10A778",
  light_green = "#5FD7A7",
  dark_purple = "#af5fd7",
  light_purple = "#a790d5",
  yellow = "#F3E430",
  light_yellow = "#ffff87",
  dark_yellow = "#A89C14",
}

return {
  base_30 = {
    black = colors.black,
    grey = colors.medium_gray,
    white = colors.white,
    subtle_black = colors.subtle_black,
    pink = colors.pink,
    red = colors.dark_red,
    blue = colors.blue,
    cyan = colors.dark_cyan,
    green = colors.dark_green,
    yellow = colors.yellow,
    purple = colors.dark_purple,
    -- You can add more colors if necessary
  },
  base_16 = {
    base00 = colors.black,
    base01 = colors.subtle_black,
    base02 = colors.light_black,
    base03 = colors.medium_gray,
    base04 = colors.lighter_gray,
    base05 = colors.white,
    base06 = colors.actual_white,
    base07 = colors.lightest_gray,
    base08 = colors.dark_red,
    base09 = colors.yellow,
    base0A = colors.yellow,
    base0B = colors.dark_green,
    base0C = colors.dark_cyan,
    base0D = colors.blue,
    base0E = colors.dark_purple,
    base0F = colors.darkest_red,
  },
}
